version: 2
sources:
  - name: raw
    database: "{{target.database}}"
    schema: DBT_DEV_SCHEMA
    tables:
      - name: customer
      - name: orders
      - name: products
      - name: transaction
